// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package server

import (
	"context"

	"dtm-go-zero/order/rpc/internal/logic"
	"dtm-go-zero/order/rpc/internal/svc"
	"dtm-go-zero/order/rpc/types/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) Create(ctx context.Context, in *order.CreateReq) (*order.CreateResp, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *OrderServer) CreateRollback(ctx context.Context, in *order.CreateReq) (*order.CreateResp, error) {
	l := logic.NewCreateRollbackLogic(ctx, s.svcCtx)
	return l.CreateRollback(in)
}
