// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	stockFieldNames          = builder.RawFieldNames(&Stock{})
	stockRows                = strings.Join(stockFieldNames, ",")
	stockRowsExpectAutoSet   = strings.Join(stringx.Remove(stockFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	stockRowsWithPlaceHolder = strings.Join(stringx.Remove(stockFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	stockModel interface {
		Insert(ctx context.Context, data *Stock) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Stock, error)
		FindOneByGoodsId(ctx context.Context, goodsId int64) (*Stock, error)
		Update(ctx context.Context, data *Stock) error
		Delete(ctx context.Context, id int64) error
	}

	defaultStockModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Stock struct {
		Id      int64 `db:"id"`
		GoodsId int64 `db:"goods_id"` // 商品id
		Num     int64 `db:"num"`      // 库存数量
	}
)

func newStockModel(conn sqlx.SqlConn) *defaultStockModel {
	return &defaultStockModel{
		conn:  conn,
		table: "`stock`",
	}
}

func (m *defaultStockModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultStockModel) FindOne(ctx context.Context, id int64) (*Stock, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", stockRows, m.table)
	var resp Stock
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStockModel) FindOneByGoodsId(ctx context.Context, goodsId int64) (*Stock, error) {
	var resp Stock
	query := fmt.Sprintf("select %s from %s where `goods_id` = ? limit 1", stockRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, goodsId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStockModel) Insert(ctx context.Context, data *Stock) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, stockRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.GoodsId, data.Num)
	return ret, err
}

func (m *defaultStockModel) Update(ctx context.Context, newData *Stock) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, stockRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.GoodsId, newData.Num, newData.Id)
	return err
}

func (m *defaultStockModel) tableName() string {
	return m.table
}
