// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: stock/rpc/order.proto

package stock

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StockClient is the client API for Stock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockClient interface {
	Deduct(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*DeductResp, error)
	DeductRollback(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*DeductResp, error)
}

type stockClient struct {
	cc grpc.ClientConnInterface
}

func NewStockClient(cc grpc.ClientConnInterface) StockClient {
	return &stockClient{cc}
}

func (c *stockClient) Deduct(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*DeductResp, error) {
	out := new(DeductResp)
	err := c.cc.Invoke(ctx, "/stock.stock/deduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockClient) DeductRollback(ctx context.Context, in *DeductReq, opts ...grpc.CallOption) (*DeductResp, error) {
	out := new(DeductResp)
	err := c.cc.Invoke(ctx, "/stock.stock/deductRollback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockServer is the server API for Stock service.
// All implementations must embed UnimplementedStockServer
// for forward compatibility
type StockServer interface {
	Deduct(context.Context, *DeductReq) (*DeductResp, error)
	DeductRollback(context.Context, *DeductReq) (*DeductResp, error)
	mustEmbedUnimplementedStockServer()
}

// UnimplementedStockServer must be embedded to have forward compatible implementations.
type UnimplementedStockServer struct {
}

func (UnimplementedStockServer) Deduct(context.Context, *DeductReq) (*DeductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deduct not implemented")
}
func (UnimplementedStockServer) DeductRollback(context.Context, *DeductReq) (*DeductResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeductRollback not implemented")
}
func (UnimplementedStockServer) mustEmbedUnimplementedStockServer() {}

// UnsafeStockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockServer will
// result in compilation errors.
type UnsafeStockServer interface {
	mustEmbedUnimplementedStockServer()
}

func RegisterStockServer(s grpc.ServiceRegistrar, srv StockServer) {
	s.RegisterService(&Stock_ServiceDesc, srv)
}

func _Stock_Deduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServer).Deduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stock.stock/deduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServer).Deduct(ctx, req.(*DeductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stock_DeductRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServer).DeductRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stock.stock/deductRollback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServer).DeductRollback(ctx, req.(*DeductReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Stock_ServiceDesc is the grpc.ServiceDesc for Stock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stock.stock",
	HandlerType: (*StockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "deduct",
			Handler:    _Stock_Deduct_Handler,
		},
		{
			MethodName: "deductRollback",
			Handler:    _Stock_DeductRollback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock/rpc/order.proto",
}
