// Code generated by goctl. DO NOT EDIT!
// Source: order.proto

package server

import (
	"context"

	"dtm-go-zero/stock/rpc/internal/logic"
	"dtm-go-zero/stock/rpc/internal/svc"
	"dtm-go-zero/stock/rpc/types/stock"
)

type StockServer struct {
	svcCtx *svc.ServiceContext
	stock.UnimplementedStockServer
}

func NewStockServer(svcCtx *svc.ServiceContext) *StockServer {
	return &StockServer{
		svcCtx: svcCtx,
	}
}

func (s *StockServer) Deduct(ctx context.Context, in *stock.DeductReq) (*stock.DeductResp, error) {
	l := logic.NewDeductLogic(ctx, s.svcCtx)
	return l.Deduct(in)
}

func (s *StockServer) DeductRollback(ctx context.Context, in *stock.DeductReq) (*stock.DeductResp, error) {
	l := logic.NewDeductRollbackLogic(ctx, s.svcCtx)
	return l.DeductRollback(in)
}
